# Generated by Django 4.2.11 on 2024-05-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Tech Blog!', max_length=255),
        ),
    ]
